

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.util.Timer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author me
 */
public class ConfirmationFrame extends javax.swing.JFrame implements AllFrames{

    /**
     * Creates new form ConfirmationFrame
     */
//    static int temp1 = Integer.parseInt(BookingFrame.DP);
    public ConfirmationFrame() {
        initComponents();
        System.gc();
        setLocationRelativeTo(this);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers","root","OOPlite");
            String sql1 = "select * from driv_info where VehicleID = ?";
            String str1 = "update driv_info set Location = ?, State = ? where VehicleID = ?";
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            PreparedStatement pstmt4 = conn.prepareStatement(str1);
            pstmt4.setInt(3,BookingFrame.nearestDriverIndex);
            pstmt1.setInt(1,BookingFrame.nearestDriverIndex);
            ResultSet rs1 = pstmt1.executeQuery();
            if(rs1.next()){
                nameTextField.setText(rs1.getString("Name"));
                phoneNumberTextField.setText(rs1.getString("PhoneNumber"));
                ratingTextField.setText(Double.toString(rs1.getDouble("Rating")));
                estimatedFareTextField.setText(Integer.toString(java.lang.Math.abs(Integer.parseInt(BookingFrame.PuP) - Integer.parseInt(BookingFrame.DP))*30) + " INR ");
                estimatedTripTimeTextField.setText(Integer.toString(java.lang.Math.abs(Integer.parseInt(BookingFrame.PuP) - Integer.parseInt(BookingFrame.DP))*15) + " minutes ");
            }
            Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","OOPlite");
            String str2 = "update user_info set Wallet = ?, State = ? where UserID = ?";
            String sql2 = "select * from user_info where UserID = ?";
            PreparedStatement pstmt2 = conn1.prepareStatement(str2);
            PreparedStatement pstmt3 = conn1.prepareStatement(sql2);
            pstmt2.setString(3, Login_Frame.uid);
            pstmt3.setString(1, Login_Frame.uid);
            ResultSet rs = pstmt3.executeQuery();
            if(rs.next()){
                pstmt2.setInt(1, Integer.parseInt(rs.getString("Wallet"))-java.lang.Math.abs(Integer.parseInt(BookingFrame.PuP)-Integer.parseInt(BookingFrame.DP))*30);
                pstmt2.setInt(2,1);
                pstmt2.executeUpdate();
                pstmt4.setInt(1,Integer.parseInt(BookingFrame.DP));
                pstmt4.setInt(2,1);
                pstmt4.executeUpdate();
            }
//            int temp = (java.lang.Math.abs(Integer.parseInt(BookingFrame.PuP) - Integer.parseInt(BookingFrame.DP)));
            Timer time = new Timer();
            TimerTask task;
            task = new TimerTask(){
                @Override
                public void run(){
                    meth();
                }
            };
            time.schedule(task,(java.lang.Math.abs(Integer.parseInt(BookingFrame.PuP) - Integer.parseInt(BookingFrame.DP)))*15*1000);
            conn.close();
            conn1.close();
        }catch(ClassNotFoundException | NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,"Here");
        }
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        bookingCOnfirmedLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JLabel();
        ratingTextField = new javax.swing.JLabel();
        estimatedFareLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        estimatedFareTextField = new javax.swing.JLabel();
        estimatedTripTimeTextField = new javax.swing.JLabel();
        homeButtonConfirmationframe = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookingCOnfirmedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookingCOnfirmedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingCOnfirmedLabel.setText("Booking Confirmed!");

        nameLabel.setText("Driver Name:");

        nameTextField.setText("?");

        phoneNumberLabel.setText("Phone Number:");

        ratingLabel.setText("Rating:");

        phoneNumberTextField.setText("?");

        ratingTextField.setText("?");

        estimatedFareLabel.setText("Estimated Fare:");

        jLabel1.setText("Estimated Trip Time:");

        estimatedFareTextField.setText("?");

        estimatedTripTimeTextField.setText("?");

        homeButtonConfirmationframe.setText("Home");
        homeButtonConfirmationframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonConfirmationframeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingCOnfirmedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estimatedFareLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ratingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estimatedFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estimatedTripTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeButtonConfirmationframe)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButtonConfirmationframe)
                .addGap(3, 3, 3)
                .addComponent(bookingCOnfirmedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedFareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estimatedFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estimatedTripTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonConfirmationframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonConfirmationframeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        hf.setVisible(true);
    }//GEN-LAST:event_homeButtonConfirmationframeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConfirmationFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingCOnfirmedLabel;
    private javax.swing.JLabel estimatedFareLabel;
    private javax.swing.JLabel estimatedFareTextField;
    private javax.swing.JLabel estimatedTripTimeTextField;
    private javax.swing.JButton homeButtonConfirmationframe;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberTextField;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel ratingTextField;
    // End of variables declaration//GEN-END:variables
    void meth(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers","root","OOPlite");
            String sql1 = "select * from driv_info where VehicleID = ?";
            String str1 = "update driv_info set Location = ?, State = ? where VehicleID = ?";
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            PreparedStatement pstmt4 = conn.prepareStatement(str1);
            pstmt4.setInt(3,BookingFrame.nearestDriverIndex);
            pstmt1.setInt(1,BookingFrame.nearestDriverIndex);
            Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","OOPlite");
            String str2 = "update user_info set Wallet = ?, State = ? where UserID = ?";
            String sql2 = "select * from user_info where UserID = ?";
            PreparedStatement pstmt2 = conn1.prepareStatement(str2);
            PreparedStatement pstmt3 = conn1.prepareStatement(sql2);
            pstmt2.setString(3, Login_Frame.uid);
            pstmt3.setString(1, Login_Frame.uid);
            ResultSet rs2 = pstmt3.executeQuery();
            if(rs2.next()){
                pstmt2.setInt(1, Integer.parseInt(rs2.getString("Wallet")));
                pstmt2.setInt(2,0);
                pstmt2.executeUpdate();
            }
            pstmt4.setInt(1,Integer.parseInt(BookingFrame.DP));
            pstmt4.setInt(2,0);
            pstmt4.executeUpdate();
            }catch(ClassNotFoundException | NumberFormatException | SQLException ex){
                JOptionPane.showMessageDialog(null, "There");
            }     
    }
}
